In [1]:
import pandas as pd

In [4]:
crop_df = pd.read_csv("crop_production_data.csv")
crop_df.head()

,state_name,district_name,crop_year,season,crop,area_,production_
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [5]:
crop_df.columns = crop_df.columns.str.strip().str.lower().str.replace(' ', '_')

In [6]:
crop_df.head()

,state_name,district_name,crop_year,season,crop,area_,production_
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [7]:
crop_df.isnull().sum()

state_name          0
district_name       0
crop_year           0
season              0
crop                0
area_               0
production_      3730
dtype: int64

In [8]:
crop_df = crop_df.dropna(subset=['production_'])
crop_df = crop_df[crop_df['production_'] > 0]
crop_df = crop_df[crop_df['area_'] > 0]

In [9]:
crop_df.isnull().sum()

state_name       0
district_name    0
crop_year        0
season           0
crop             0
area_            0
production_      0
dtype: int64

In [10]:
crop_df = (
    crop_df.groupby(['state_name', 'crop_year', 'season', 'crop'], as_index=False)
    .agg({'area_': 'sum', 'production_': 'sum'})
)

crop_df['yield_'] = crop_df['production_'] / crop_df['area_']

crop_df = crop_df.sort_values(by=['state_name', 'crop_year', 'season', 'crop']).reset_index(drop=True)

crop_df.head()

,state_name,crop_year,season,crop,area_,production_,yield_
0,Andaman and Nicobar Islands,2000,Kharif,Arecanut,4354.0,7200.0,1.653652
1,Andaman and Nicobar Islands,2000,Kharif,Other Kharif pulses,670.0,449.0,0.670149
2,Andaman and Nicobar Islands,2000,Kharif,Rice,10881.0,32184.0,2.957816
3,Andaman and Nicobar Islands,2000,Whole Year,Banana,1707.0,12714.0,7.448155
4,Andaman and Nicobar Islands,2000,Whole Year,Cashewnut,800.0,219.0,0.273750

In [12]:
print("Unique States:", crop_df['state_name'].nunique())
print(crop_df['state_name'].unique())

print("\nUnique Seasons:", crop_df['season'].nunique())
print(crop_df['season'].unique())

print("\nUnique Crops:", crop_df['crop'].nunique())
print(crop_df['crop'].unique())

Unique States: 33
['Andaman and Nicobar Islands' 'Andhra Pradesh' 'Arunachal Pradesh'
 'Assam' 'Bihar' 'Chandigarh' 'Chhattisgarh' 'Dadra and Nagar Haveli'
 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh' 'Jammu and Kashmir'
 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh' 'Maharashtra' 'Manipur'
 'Meghalaya' 'Mizoram' 'Nagaland' 'Odisha' 'Puducherry' 'Punjab'
 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Telangana' 'Tripura' 'Uttar Pradesh'
 'Uttarakhand' 'West Bengal']

Unique Seasons: 6
['Kharif' 'Whole Year' 'Autumn' 'Rabi' 'Summer' 'Winter']

Unique Crops: 105
['Arecanut' 'Other Kharif pulses' 'Rice' 'Banana' 'Cashewnut' 'Coconut'
 'Dry ginger' 'Sugarcane' 'Sweet potato' 'Tapioca' 'other oilseeds'
 'Black pepper' 'Dry chillies' 'Turmeric' 'Arhar/Tur' 'Groundnut' 'Maize'
 'Moong(Green Gram)' 'Sunflower' 'Urad' 'Bajra' 'Castor seed'
 'Cotton(lint)' 'Horse-gram' 'Jowar' 'Korra' 'Mesta' 'Ragi' 'Samai'
 'Sesamum' 'Small millets' 'Tobacco' 'Gram' 'Varagu' 'Wheat'
 'Other  Rabi pulses' 'Masoor' 'Niger seed' 'Linseed' 'Rapeseed &Mustard'
 'Safflower' 'Onion' 'other misc. pulses' 'Coriander' 'Potato'
 'Beans & Mutter(Vegetable)' 'Bhindi' 'Brinjal' 'Citrus Fruit' 'Grapes'
 'Mango' 'Orange' 'Other Fresh Fruits' 'Papaya' 'Pome Fruit' 'Tomato'
 'Soyabean' 'Garlic' 'Ginger' 'Cowpea(Lobia)' 'Cabbage' 'Lemon'
 'Pome Granet' 'Sapota' 'Oilseeds total' 'Pulses total' 'Jute'
 'Peas & beans (Pulses)' 'Pineapple' 'Blackgram' 'Paddy' 'Barley'
 'Sannhamp' 'Khesari' 'Guar seed' 'Other Vegetables' 'Moth'
 'Other Cereals & Millets' 'Cond-spcs other' 'Carrot' 'Redish' 'Turnip'
 'Cardamom' 'Arcanut (Processed)' 'Atcanut (Raw)' 'Cashewnut Processed'
 'Cashewnut Raw' 'Coffee' 'Rubber' 'Tea' 'Drum Stick' 'Jack Fruit'
 'Total foodgrain' 'Kapas' 'Bitter Gourd' 'Bottle Gourd' 'Cauliflower'
 'Bean' 'Colocosia' 'Jobster' 'Perilla' 'Rajmash Kholar'
 'Ricebean (nagadal)' 'Lentil' 'Jute & mesta']

In [13]:
print("Year range:", crop_df['crop_year'].min(), "to", crop_df['crop_year'].max())

Year range: 1997 to 2015

In [14]:
rain_df = pd.read_csv("rainfall_data.csv")
rain_df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JF,MAM,JJAS,OND
0,Andaman & Nicobar Islands,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,Andaman & Nicobar Islands,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,Andaman & Nicobar Islands,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,Andaman & Nicobar Islands,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,Andaman & Nicobar Islands,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [15]:
rain_df = rain_df[(rain_df['YEAR'] >= 1997) & (rain_df['YEAR'] <= 2015)]

In [16]:
rain_df = rain_df.drop(columns=['JF', 'MAM', 'JJAS', 'OND'], errors='ignore')

In [17]:
rain_df.isnull().sum()

SUBDIVISION    0
YEAR           0
JAN            1
FEB            1
MAR            0
APR            0
MAY            0
JUN            0
JUL            1
AUG            0
SEP            0
OCT            0
NOV            1
DEC            1
ANNUAL         3
dtype: int64

In [18]:
rain_df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL
91,Andaman & Nicobar Islands,1997,9.5,0.0,0.2,15.6,281.1,199.5,918.5,430.6,440.2,128.7,292.8,38.4,2755.1
92,Andaman & Nicobar Islands,1998,0.9,0.0,0.0,0.0,348.9,600.0,364.5,258.9,337.8,618.6,227.8,89.0,2846.4
93,Andaman & Nicobar Islands,1999,46.8,44.6,14.2,270.6,257.4,295.0,408.5,329.2,325.3,437.5,124.9,145.7,2699.7
94,Andaman & Nicobar Islands,2000,53.0,59.0,171.3,218.1,422.8,357.0,176.3,460.8,250.1,321.2,158.3,115.2,2763.2
95,Andaman & Nicobar Islands,2001,89.0,15.7,143.3,30.1,705.3,370.7,341.3,469.0,334.4,267.6,222.6,91.8,3080.9

In [20]:
rain_df['ANNUAL'] = rain_df[['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']].sum(axis=1)
print(rain_df['ANNUAL'].isnull().sum())
rain_df.head()

0

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL
91,Andaman & Nicobar Islands,1997,9.5,0.0,0.2,15.6,281.1,199.5,918.5,430.6,440.2,128.7,292.8,38.4,2755.1
92,Andaman & Nicobar Islands,1998,0.9,0.0,0.0,0.0,348.9,600.0,364.5,258.9,337.8,618.6,227.8,89.0,2846.4
93,Andaman & Nicobar Islands,1999,46.8,44.6,14.2,270.6,257.4,295.0,408.5,329.2,325.3,437.5,124.9,145.7,2699.7
94,Andaman & Nicobar Islands,2000,53.0,59.0,171.3,218.1,422.8,357.0,176.3,460.8,250.1,321.2,158.3,115.2,2763.1
95,Andaman & Nicobar Islands,2001,89.0,15.7,143.3,30.1,705.3,370.7,341.3,469.0,334.4,267.6,222.6,91.8,3080.8

In [21]:
rain_df = rain_df.fillna(0)

In [22]:
rain_df = rain_df.rename(columns={
    'SUBDIVISION': 'state_name',
    'YEAR': 'crop_year'
})

In [23]:
rain_df.head()

,state_name,crop_year,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL
91,Andaman & Nicobar Islands,1997,9.5,0.0,0.2,15.6,281.1,199.5,918.5,430.6,440.2,128.7,292.8,38.4,2755.1
92,Andaman & Nicobar Islands,1998,0.9,0.0,0.0,0.0,348.9,600.0,364.5,258.9,337.8,618.6,227.8,89.0,2846.4
93,Andaman & Nicobar Islands,1999,46.8,44.6,14.2,270.6,257.4,295.0,408.5,329.2,325.3,437.5,124.9,145.7,2699.7
94,Andaman & Nicobar Islands,2000,53.0,59.0,171.3,218.1,422.8,357.0,176.3,460.8,250.1,321.2,158.3,115.2,2763.1
95,Andaman & Nicobar Islands,2001,89.0,15.7,143.3,30.1,705.3,370.7,341.3,469.0,334.4,267.6,222.6,91.8,3080.8

In [24]:
print(rain_df['state_name'].unique())

['Andaman & Nicobar Islands' 'Arunachal Pradesh' 'Assam & Meghalaya'
 'Naga Mani Mizo Tripura' 'Sub Himalayan West Bengal & Sikkim'
 'Gangetic West Bengal' 'Orissa' 'Jharkhand' 'Bihar' 'East Uttar Pradesh'
 'West Uttar Pradesh' 'Uttarakhand' 'Haryana Delhi & Chandigarh' 'Punjab'
 'Himachal Pradesh' 'Jammu & Kashmir' 'West Rajasthan' 'East Rajasthan'
 'West Madhya Pradesh' 'East Madhya Pradesh' 'Gujarat Region'
 'Saurashtra & Kutch' 'Konkan & Goa' 'Madhya Maharashtra' 'Matathwada'
 'Vidarbha' 'Chhattisgarh' 'Coastal Andhra Pradesh' 'Telangana'
 'Rayalseema' 'Tamil Nadu' 'Coastal Karnataka' 'North Interior Karnataka'
 'South Interior Karnataka' 'Kerala' 'Lakshadweep']

In [27]:
multi_state_groups = [
    'Assam & Meghalaya',
    'Naga Mani Mizo Tripura',
    'Sub Himalayan West Bengal & Sikkim',
    'Haryana Delhi & Chandigarh',
    'Konkan & Goa',
    'Coastal Andhra Pradesh',
    'Rayalseema',
    'Coastal Karnataka',
    'North Interior Karnataka',
    'South Interior Karnataka'
]

# Drop only those rows
rain_df_cleaned = rain_df[~rain_df['state_name'].isin(multi_state_groups)].copy()
print(rain_df_cleaned['state_name'].unique())

['Andaman & Nicobar Islands' 'Arunachal Pradesh' 'Gangetic West Bengal'
 'Orissa' 'Jharkhand' 'Bihar' 'East Uttar Pradesh' 'West Uttar Pradesh'
 'Uttarakhand' 'Punjab' 'Himachal Pradesh' 'Jammu & Kashmir'
 'West Rajasthan' 'East Rajasthan' 'West Madhya Pradesh'
 'East Madhya Pradesh' 'Gujarat Region' 'Saurashtra & Kutch'
 'Madhya Maharashtra' 'Matathwada' 'Vidarbha' 'Chhattisgarh' 'Telangana'
 'Tamil Nadu' 'Kerala' 'Lakshadweep']

In [43]:
rename_to_state = {
    'Andaman & Nicobar Islands': 'Andaman and Nicobar Islands',
    'Orissa': 'Odisha',
    'East Uttar Pradesh': 'Uttar Pradesh',
    'West Uttar Pradesh': 'Uttar Pradesh',
    'West Rajasthan': 'Rajasthan',
    'East Rajasthan': 'Rajasthan',
    'West Madhya Pradesh': 'Madhya Pradesh',
    'East Madhya Pradesh': 'Madhya Pradesh',
    'Gujarat Region': 'Gujarat',
    'Saurashtra & Kutch': 'Gujarat',
    'Madhya Maharashtra': 'Maharashtra',
    'Matathwada': 'Maharashtra',
    'Vidarbha': 'Maharashtra',
    'Gangetic West Bengal': 'West Bengal',
    'Jammu & Kashmir': 'Jammu and Kashmir'
}

rain_df_cleaned['state_name'] = rain_df_cleaned['state_name'].replace(rename_to_state)

In [44]:
rain_df_yearly = (
    rain_df_cleaned
    .groupby(['state_name', 'crop_year'], as_index=False)
    .mean()
)

In [45]:
print(rain_df_yearly['state_name'].unique())

['Andaman and Nicobar Islands' 'Arunachal Pradesh' 'Bihar' 'Chhattisgarh'
 'Gujarat' 'Himachal Pradesh' 'Jammu and Kashmir' 'Jharkhand' 'Kerala'
 'Lakshadweep' 'Madhya Pradesh' 'Maharashtra' 'Odisha' 'Punjab'
 'Rajasthan' 'Tamil Nadu' 'Telangana' 'Uttar Pradesh' 'Uttarakhand'
 'West Bengal']

In [46]:
rain_states = set(rain_df_yearly['state_name'].unique())
crop_states = set(crop_df['state_name'].unique())

common_states = rain_states.intersection(crop_states)

rain_df_final = rain_df_yearly[rain_df_yearly['state_name'].isin(common_states)].copy()
crop_df_final = crop_df[crop_df['state_name'].isin(common_states)].copy()

rain_only = sorted(rain_states - crop_states)
crop_only = sorted(crop_states - rain_states)

print("Common states:", sorted(common_states))
print("In rain_df only:", rain_only)
print("In crop_df only:", crop_only)

Common states: ['Andaman and Nicobar Islands', 'Arunachal Pradesh', 'Bihar', 'Chhattisgarh', 'Gujarat', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']
In rain_df only: ['Lakshadweep']
In crop_df only: ['Andhra Pradesh', 'Assam', 'Chandigarh', 'Dadra and Nagar Haveli', 'Goa', 'Haryana', 'Karnataka', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Puducherry', 'Sikkim', 'Tripura']

In [47]:
rain_df_final['Kharif'] = rain_df_final[['JUN', 'JUL', 'AUG', 'SEP']].sum(axis=1)
rain_df_final['Rabi'] = rain_df_final[['OCT', 'NOV', 'DEC', 'JAN', 'FEB', 'MAR']].sum(axis=1)
rain_df_final['Summer'] = rain_df_final[['APR', 'MAY']].sum(axis=1)
rain_df_final['Winter'] = rain_df_final[['JAN', 'FEB']].sum(axis=1)
rain_df_final['Autumn'] = rain_df_final[['OCT', 'NOV']].sum(axis=1)

In [48]:
month_cols = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']

rain_df_final = rain_df_final.drop(columns=month_cols)

In [49]:
rain_df_final.head()

,state_name,crop_year,ANNUAL,Kharif,Rabi,Summer,Winter,Autumn
0,Andaman and Nicobar Islands,1997,2755.1,1988.8,469.6,296.7,9.5,421.5
1,Andaman and Nicobar Islands,1998,2846.4,1561.2,936.3,348.9,0.9,846.4
2,Andaman and Nicobar Islands,1999,2699.7,1358.0,813.7,528.0,91.4,562.4
3,Andaman and Nicobar Islands,2000,2763.1,1244.2,878.0,640.9,112.0,479.5
4,Andaman and Nicobar Islands,2001,3080.8,1515.4,830.0,735.4,104.7,490.2

In [50]:
rain_df_final = rain_df_final.rename(columns={'ANNUAL': 'Whole Year'})

In [51]:
rain_df_final.head()

,state_name,crop_year,Whole Year,Kharif,Rabi,Summer,Winter,Autumn
0,Andaman and Nicobar Islands,1997,2755.1,1988.8,469.6,296.7,9.5,421.5
1,Andaman and Nicobar Islands,1998,2846.4,1561.2,936.3,348.9,0.9,846.4
2,Andaman and Nicobar Islands,1999,2699.7,1358.0,813.7,528.0,91.4,562.4
3,Andaman and Nicobar Islands,2000,2763.1,1244.2,878.0,640.9,112.0,479.5
4,Andaman and Nicobar Islands,2001,3080.8,1515.4,830.0,735.4,104.7,490.2

In [52]:
crop_df_final.head()

,state_name,crop_year,season,crop,area_,production_,yield_
0,Andaman and Nicobar Islands,2000,Kharif,Arecanut,4354.0,7200.0,1.653652
1,Andaman and Nicobar Islands,2000,Kharif,Other Kharif pulses,670.0,449.0,0.670149
2,Andaman and Nicobar Islands,2000,Kharif,Rice,10881.0,32184.0,2.957816
3,Andaman and Nicobar Islands,2000,Whole Year,Banana,1707.0,12714.0,7.448155
4,Andaman and Nicobar Islands,2000,Whole Year,Cashewnut,800.0,219.0,0.273750

In [53]:
rain_seasonal = rain_df_final.melt(
    id_vars=['state_name', 'crop_year'],
    value_vars=['Whole Year', 'Kharif', 'Rabi', 'Summer', 'Winter', 'Autumn'],
    var_name='season',
    value_name='rainfall_mm'
)

In [54]:
merged_df = crop_df_final.merge(
    rain_seasonal,
    on=['state_name', 'crop_year', 'season'],
    how='inner'
)
print(merged_df.head())
print(merged_df.shape)

                    state_name  crop_year      season                 crop  \
0  Andaman and Nicobar Islands       2000      Kharif             Arecanut
1  Andaman and Nicobar Islands       2000      Kharif  Other Kharif pulses
2  Andaman and Nicobar Islands       2000      Kharif                 Rice
3  Andaman and Nicobar Islands       2000  Whole Year               Banana
4  Andaman and Nicobar Islands       2000  Whole Year            Cashewnut

     area_  production_    yield_  rainfall_mm
0   4354.0       7200.0  1.653652       1244.2
1    670.0        449.0  0.670149       1244.2
2  10881.0      32184.0  2.957816       1244.2
3   1707.0      12714.0  7.448155       2763.1
4    800.0        219.0  0.273750       2763.1
(9262, 8)

In [55]:
merged_df.to_csv('final_dataset.csv', index=False)